// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr22fwiHZetkVKGBGTmApTE1AIXNirq10',
    appId: '1:407918042181:web:52de9cc1b4830adcff172c',
    messagingSenderId: '407918042181',
    projectId: 'gr01-secret-sorcerer-2025-fall',
    authDomain: 'gr01-secret-sorcerer-2025-fall.firebaseapp.com',
    storageBucket: 'gr01-secret-sorcerer-2025-fall.firebasestorage.app',
    measurementId: 'G-KDLMRHRRNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2fW3k3Z4dDCKZ-8cQ9m0jwxrYjjlm_XY',
    appId: '1:407918042181:android:0cd57bf84081e1bdff172c',
    messagingSenderId: '407918042181',
    projectId: 'gr01-secret-sorcerer-2025-fall',
    storageBucket: 'gr01-secret-sorcerer-2025-fall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrBqulVZ4qrx3okWPnidMr5KFLNGuD0k',
    appId: '1:407918042181:ios:b2fe953565a0c045ff172c',
    messagingSenderId: '407918042181',
    projectId: 'gr01-secret-sorcerer-2025-fall',
    storageBucket: 'gr01-secret-sorcerer-2025-fall.firebasestorage.app',
    iosBundleId: 'com.example.secretSorcerer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvrBqulVZ4qrx3okWPnidMr5KFLNGuD0k',
    appId: '1:407918042181:ios:b2fe953565a0c045ff172c',
    messagingSenderId: '407918042181',
    projectId: 'gr01-secret-sorcerer-2025-fall',
    storageBucket: 'gr01-secret-sorcerer-2025-fall.firebasestorage.app',
    iosBundleId: 'com.example.secretSorcerer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr22fwiHZetkVKGBGTmApTE1AIXNirq10',
    appId: '1:407918042181:web:1a7d28e780668260ff172c',
    messagingSenderId: '407918042181',
    projectId: 'gr01-secret-sorcerer-2025-fall',
    authDomain: 'gr01-secret-sorcerer-2025-fall.firebaseapp.com',
    storageBucket: 'gr01-secret-sorcerer-2025-fall.firebasestorage.app',
    measurementId: 'G-TJSS9SXTEC',
  );
}
